export const CHANGE_FILTER_TYPE = 'CHANGE_FILTER_TYPE';
export const SET_PRODUCT = 'SET_PRODUCT';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';